spring.application.name=section1


# If username property is not provided in properties, then default username is "user"
# If password property is not provided in properties, then default password is printed on the console during application startup
spring.security.user.name=lokesh
spring.security.user.password=mittal


# enabling TRACE logging only spring security related classes
logging.level.org.springframework.security=TRACE
